# Generated by Django 4.2.3 on 2023-08-10 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=64)),
                ("fullname", models.CharField(max_length=64)),
                ("gender", models.CharField(max_length=64)),
                ("birthdate", models.DateField(max_length=64)),
                ("phone", models.CharField(max_length=64)),
                ("mail", models.CharField(max_length=64)),
                ("rq_terms", models.BooleanField(default=0)),
                ("op_terms", models.BooleanField(default=0)),
                ("image", models.ImageField(null=True, upload_to="photos/")),
                ("sign_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
