# Generated by Django 4.2.3 on 2023-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_profile_nickname_alter_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(max_length=64),
        ),
    ]
