# Generated by Django 4.2.3 on 2023-09-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_profile_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="mail",
        ),
    ]
