# Generated by Django 4.2.3 on 2023-08-14 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("name", models.CharField(max_length=64)),
                ("rating", models.FloatField(null=True)),
                ("review_total", models.IntegerField(null=True)),
                ("address_si", models.CharField(max_length=32)),
                ("address_gu", models.CharField(max_length=32)),
                ("address_dong", models.CharField(max_length=32)),
                ("address_detail", models.CharField(blank=True, max_length=32)),
                ("contact", models.CharField(max_length=16)),
                ("period_start", models.DateTimeField(null=True)),
                ("period_end", models.DateTimeField(null=True)),
                ("duration", models.CharField(max_length=32, null=True)),
                ("url", models.CharField(max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="place_like_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="Z0", max_length=32, unique=True)),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(null=True)),
                (
                    "title",
                    models.CharField(
                        default="<django.db.models.fields.DateTimeField>의 플랜",
                        max_length=64,
                    ),
                ),
                ("except_time1", models.IntegerField(null=True)),
                ("except_time2", models.IntegerField(null=True)),
                ("except_time3", models.IntegerField(null=True)),
                ("hashtag_area", models.CharField(blank=True, max_length=32)),
                ("hashtag_type", models.CharField(blank=True, max_length=32)),
                ("hashtag_pick", models.CharField(blank=True, max_length=32)),
                ("memo", models.TextField()),
                ("public", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                ("removed_at", models.BooleanField(null=True)),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="plan_like_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "place1_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place1",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "place2_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place2",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "place3_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place3",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "place4_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place4",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPlanView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Day_Pl.plan"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Day_Pl.placetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Day_Pl.plan"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="type_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Day_Pl.placetype",
            ),
        ),
    ]
