# Generated by Django 4.2.3 on 2023-08-10 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=64)),
                ("rating", models.FloatField(null=True)),
                ("review_total", models.IntegerField(null=True)),
                ("address_si", models.CharField(max_length=32)),
                ("address_gu", models.CharField(max_length=32)),
                ("address_dong", models.CharField(max_length=32)),
                ("address_detail", models.CharField(blank=True, max_length=32)),
                ("contact", models.CharField(max_length=16)),
                ("period_start", models.DateTimeField(null=True)),
                ("period_end", models.DateTimeField(null=True)),
                ("mon_open_time", models.DateTimeField(null=True)),
                ("mon_close_time", models.DateTimeField(null=True)),
                ("tue_open_time", models.DateTimeField(null=True)),
                ("tue_close_time", models.DateTimeField(null=True)),
                ("wed_open_time", models.DateTimeField(null=True)),
                ("wed_close_time", models.DateTimeField(null=True)),
                ("thu_open_time", models.DateTimeField(null=True)),
                ("thu_close_time", models.DateTimeField(null=True)),
                ("fri_open_time", models.DateTimeField(null=True)),
                ("fri_close_time", models.DateTimeField(null=True)),
                ("sat_open_time", models.DateTimeField(null=True)),
                ("sat_close_time", models.DateTimeField(null=True)),
                ("sun_open_time", models.DateTimeField(null=True)),
                ("sun_close_time", models.DateTimeField(null=True)),
                ("duration", models.CharField(max_length=32, null=True)),
                ("url", models.CharField(max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="place_like_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(null=True)),
                (
                    "title",
                    models.CharField(
                        default="<django.db.models.fields.DateTimeField>의 플랜",
                        max_length=64,
                    ),
                ),
                ("except_time1", models.IntegerField(null=True)),
                ("except_time2", models.IntegerField(null=True)),
                ("except_time3", models.IntegerField(null=True)),
                ("hashtag_area", models.CharField(blank=True, max_length=32)),
                ("hashtag_type", models.CharField(blank=True, max_length=32)),
                ("hashtag_pick", models.CharField(blank=True, max_length=32)),
                ("memo", models.TextField()),
                ("public", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                ("removed_at", models.BooleanField(null=True)),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="plan_like_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "place1_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place1",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "place2_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place2",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "place3_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place3",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "place4_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place4",
                        to="Day_Pl.place",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amusement_park", models.BooleanField(default=True)),
                ("zoo", models.BooleanField(default=True)),
                ("plant", models.BooleanField(default=True)),
                ("walk", models.BooleanField(default=True)),
                ("bike", models.BooleanField(default=True)),
                ("skate", models.BooleanField(default=True)),
                ("hike", models.BooleanField(default=True)),
                ("aquarium", models.BooleanField(default=True)),
                ("spa", models.BooleanField(default=True)),
                ("shopping", models.BooleanField(default=True)),
                ("movie", models.BooleanField(default=True)),
                ("cafe", models.BooleanField(default=True)),
                ("cartoon", models.BooleanField(default=True)),
                ("dog", models.BooleanField(default=True)),
                ("cat", models.BooleanField(default=True)),
                ("cooking", models.BooleanField(default=True)),
                ("perfume", models.BooleanField(default=True)),
                ("ceramic", models.BooleanField(default=True)),
                ("ring", models.BooleanField(default=True)),
                ("alcohol", models.BooleanField(default=True)),
                ("drawing", models.BooleanField(default=True)),
                ("dance", models.BooleanField(default=True)),
                ("flower", models.BooleanField(default=True)),
                ("boardgame", models.BooleanField(default=True)),
                ("escaperoom", models.BooleanField(default=True)),
                ("gameroom", models.BooleanField(default=True)),
                ("screen_baseball", models.BooleanField(default=True)),
                ("bawling", models.BooleanField(default=True)),
                ("musical", models.BooleanField(default=True)),
                ("play", models.BooleanField(default=True)),
                ("concert", models.BooleanField(default=True)),
                ("exhibition", models.BooleanField(default=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPlanView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Day_Pl.plan"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Day_Pl.placetype",
            ),
        ),
    ]
