# Generated by Django 4.2.3 on 2023-08-14 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planplace",
            old_name="plan_id",
            new_name="plan",
        ),
        migrations.RenameField(
            model_name="userplanview",
            old_name="plan_id",
            new_name="plan",
        ),
        migrations.RenameField(
            model_name="userplanview",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="place",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="place1_id",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="place2_id",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="place3_id",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="place4_id",
        ),
        migrations.AddField(
            model_name="place",
            name="expected_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="planplace",
            name="place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Day_Pl.place",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
