# Generated by Django 4.2.3 on 2023-08-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0002_rename_plan_id_planplace_plan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="address_dong",
            new_name="address_lo",
        ),
    ]
