# Generated by Django 4.2.3 on 2023-08-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0005_alter_plan_memo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="expected_time",
            new_name="expected_time_during",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="except_time1",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="except_time2",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="except_time3",
        ),
        migrations.AddField(
            model_name="planplace",
            name="expected_time_from_this",
            field=models.IntegerField(null=True),
        ),
    ]
