# Generated by Django 4.2.3 on 2023-08-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0008_alter_plan_memo_alter_plan_removed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
