# Generated by Django 4.2.3 on 2023-08-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0010_alter_plan_like_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planplace",
            name="expected_time_from_this",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
