# Generated by Django 4.2.3 on 2023-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0011_alter_planplace_expected_time_from_this"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="total_time",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
