# Generated by Django 4.2.3 on 2023-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0013_remove_planplace_expected_time_from_this_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planplace",
            name="expected_time_from_this",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
