# Generated by Django 4.2.3 on 2023-08-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0014_planplace_expected_time_from_this"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="naver_place_id",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
