# Generated by Django 4.2.3 on 2023-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0015_place_naver_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="planplace",
            name="road_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
