# Generated by Django 4.2.3 on 2023-08-28 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Day_Pl", "0016_planplace_road_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="view_users",
            field=models.ManyToManyField(
                related_name="plans_view",
                through="Day_Pl.UserPlanView",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
