# Generated by Django 4.2.3 on 2023-09-08 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Day_Pl", "0019_remove_plan_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="type_code_big",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="like_users",
            field=models.ManyToManyField(
                related_name="like_plans", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="view_users",
            field=models.ManyToManyField(
                related_name="view_plans",
                through="Day_Pl.UserPlanView",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
