# Generated by Django 4.2.3 on 2023-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0021_plancomment_placecomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceTypeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="Z", max_length=32, unique=True)),
                ("name", models.CharField(max_length=32)),
            ],
        ),
    ]
