# Generated by Django 4.2.3 on 2023-09-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0022_placetypecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="placetype",
            name="place_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Day_Pl.placetypecategory",
            ),
        ),
    ]
