# Generated by Django 4.2.3 on 2023-09-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0023_placetype_place_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="placetype",
            old_name="place_category",
            new_name="category",
        ),
    ]
