# Generated by Django 4.2.3 on 2023-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0024_rename_place_category_placetype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="placecomment",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plancomment",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
