# Generated by Django 4.2.3 on 2023-09-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Day_Pl", "0026_alter_placecomment_place_alter_plancomment_place"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plancomment",
            old_name="place",
            new_name="plan",
        ),
    ]
